version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - regexpMust
    revive:
      # unused-parameter is excluded due to methods with TODO implementation
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
